shared:
  - status: exception
    messages:
      - "DELIVERY EXCEPTION"
      - "INTERNATIONAL HUB SCAN - EXCEPTION"
      - "CUSTOMS CLEARANCE EXCEPTION"
      - "UNABLE TO DELIVER TRANSPORT INCIDENT"
      - "UNABLE TO DELIVER, NO PIN CODE PROVIDED"
      - "HELD AT DEPOT"
      - "DIVERSION REQUESTED AND RELABELED"
      - "MISROUTED"

  - status: returned
    messages:
      - "REFUSED DELIVERY"
      - "REFUSED - DELIVERY ADDRESS QUERY"
      - "COLLECTION REFUSED"
      - "RETURN TO SENDER - UNABLE TO DELIVER"
      - "RETURNED TO SENDER - TAX NOT PAID"
      - "RETURN TO SENDER AS INCORRECT HS CODE"
      - "RETURN TO SENDER AS INCORRECT IOSS"
      - "RETURN TO SENDER AS HS CODE ERROR"
      - "RETURN TO SENDER AS IOSS ERROR"

  - status: failure
    messages:
      - "DELIVERY ATTEMPTED"
      - "DELIVERY ATTEMPTED - NO ACCESS TO ADDRESS"
      - "UNABLE TO DELIVER - DRIVER TO RE-ATTEMPT"
      - "DELIVERY ATTEMPTED - NO PAYMENT WILL REATTEMPT"
      - "DELIVERY WILL BE ATTEMPTED BETWEEN 07:00 AND 08:00"
      - "DELIVERY WILL BE ATTEMPTED BETWEEN 07:30 AND 08:30"
      - "DELIVERY WILL BE ATTEMPTED BETWEEN 08:00 AND 09:00"
      - "DELIVERY WILL BE ATTEMPTED BETWEEN 08:30 AND 09:30"
      - "DELIVERY WILL BE ATTEMPTED BETWEEN 09:00 AND 10:00"
      - "DELIVERY WILL BE ATTEMPTED BETWEEN 09:30 AND 10:30"
      - "DELIVERY WILL BE ATTEMPTED BETWEEN 10:00 AND 11:00"
      - "DELIVERY WILL BE ATTEMPTED BETWEEN 10:30 AND 11:30"
      - "DELIVERY WILL BE ATTEMPTED BETWEEN 11:00 AND 12:00"
      - "DELIVERY WILL BE ATTEMPTED BETWEEN 11:30 AND 12:30"
      - "DELIVERY WILL BE ATTEMPTED BETWEEN 12:00 AND 13:00"
      - "DELIVERY WILL BE ATTEMPTED BETWEEN 12:30 AND 13:30"
      - "DELIVERY WILL BE ATTEMPTED BETWEEN 13:00 AND 14:00"
      - "DELIVERY WILL BE ATTEMPTED BETWEEN 13:30 AND 14:30"
      - "DELIVERY WILL BE ATTEMPTED BETWEEN 14:00 AND 15:00"
      - "DELIVERY WILL BE ATTEMPTED BETWEEN 14:30 AND 15:30"
      - "DELIVERY WILL BE ATTEMPTED BETWEEN 15:00 AND 16:00"
      - "DELIVERY WILL BE ATTEMPTED BETWEEN 15:30 AND 16:30"
      - "DELIVERY WILL BE ATTEMPTED BETWEEN 16:00 AND 17:00"
      - "DELIVERY WILL BE ATTEMPTED BETWEEN 16:30 AND 17:30"
      - "DELIVERY WILL BE ATTEMPTED BETWEEN 17:00 AND 18:00"
      - "DELIVERY WILL BE ATTEMPTED BETWEEN 17:30 AND 18:30"
      - "DELIVERY WILL BE ATTEMPTED BETWEEN 18:00 AND 19:00"
      - "DELIVERY WILL BE ATTEMPTED BETWEEN 18:30 AND 19:30"
      - "DELIVERY WILL BE ATTEMPTED BETWEEN 19:00 AND 20:00"
      - "DELIVERY WILL BE ATTEMPTED BETWEEN 19:30 AND 20:30"
      - "DELIVERY WILL BE ATTEMPTED BETWEEN 20:00 AND 21:00"
      - "DELIVERY ATTEMPTED - WILL DIVERT TO PARCEL SHOP"

  - status: waiting
    messages:
      - "PARCEL DATA RECEIVED - AWAITING CARRIER SCAN"
      - "HELD FOR COLLECTION"
